<?php


namespace EvolutionCMS\Services\AmountCalculators;


class TestCalculator extends CalculatorDecorator
{
    public function calculate($formData): float
    {
        $sum = parent::calculate($formData); // TODO: Change the autogenerated stub
        $sum += 1;
        return $sum;
    }
}